### ISSUE TITLE
Heartbeat support

### ISSUE THREAD

**Issue by JSteunou** [rabbitmq/rabbitmq-web-stomp#11]
I know SockJS does not support heartbeat, but could it be possible to implement it on this plugin side?

I look at stomp.js and how @jmesnil did it, and he just add a ping & a pong by hand. I really think that's the way to do it, because ping/pong not gonna land into websocket before a while (maybe never) so SockJS wont implement it.

**Comment by michaelklishin** [comment]
This repository is a mirror.

This is a duplicate of #8, also discussed on the mailing list. We are open to doing that but quite stretched at the moment.

**Comment by JSteunou** [comment]
Roger that, thank you @michaelklishin
