### ISSUE TITLE
Support client certificate authentication

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-web-stomp#116]
The `rabbitmq-web-stomp` plugin does not currently support client certificate authentication.

Reported [here](https://community.pivotal.io/s/question/0D50e0000650Ep8/how-to-enable-the-webstomp-using-ssl-without-implicit-usage-of-the-guest-user-for-creating-the-channel) for Web STOMP.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.
