### ISSUE TITLE
Support queue naming when subscribing to topics/exchanges

### ISSUE THREAD

**Issue by dynamed-dev** [rabbitmq/rabbitmq-web-stomp#129]
We need a structure in which it is possible to assign a fixed queue to a client, which is not deleted when the client logs off. 
The reason is that we have to store persistent messages in this queue until they are picked up by this client.

Such a feature has already been implemented for the rabbitmq-stomp plugin.
>>https://github.com/rabbitmq/rabbitmq-stomp/issues/43

The goal would be to be able to enter a name for the queue in the subscription options. 
If this named queue exists, the client could register as a consumer for this queue.

**Comment by michaelklishin** [comment]
The "feature" you are referring to is used by specifying [some relevant STOMP headers](https://www.rabbitmq.com/stomp.html#d.dts). There should be nothing to do on the Web STOMP part. If there is and you have a specific example that we can use to reproduce/understand what's missing, please file a new issue with the details.

**Comment by michaelklishin** [comment]
Hm, I guess it's a combination of a certain [destination type](https://www.rabbitmq.com/stomp.html#d) and relevant `SUBSCRIBE` frame headers. All of which should be available already to your STOMP-over-WebSockets client library.

**Comment by phil16727** [comment]
I Michal,
Well the issue he quoted was that STOMP ignored the Header „x-queue-Name“ this was fixed in 2015. unfortunately stomp over WebSocket is still ignoring x-queue-Name in the header field.

**Comment by michaelklishin** [comment]
This plugin for the most part forwards frames received over WebSockets to a "regular" STOMP connection. It does not process `SUBSCRIBE` frames directly. You have to back your claims with evidence (a way to reproduce).

**Comment by phil16727** [comment]
Hey Michael,
Well we where able to „subscribe“ to an Exchange with the type „topic“ so there is no issue with that. 

Add the header „auto-delete“:false works as well.
Adding x_queue_name“:“mysubsciption-xyz“ won’t work. 

In the Moment I was writing i am getting completely insecure if we have maybe missspelled 
The header instead of x_queue_name we perhaps used x-queue-name. 
I double check and if this is not the case I post the example.

**Comment by michaelklishin** [comment]
@phil16727 what leads you to believe that the header name is `x_queue_name`? STOMP header naming convention closely resembles that of HTTP. What you see suggested by a user in an issue is not necessarily what we end up doing.

The name of the header is `x-queue-name` as [the STOMP guide suggests](https://www.rabbitmq.com/stomp.html#d.ugqn).

**Comment by phil16727** [comment]
Hi @michaelklishin ,
So nevertheless I will double check on Monday if the spelling is right. If it is, I open up a new issue with a source code example of how we subscribed a the assigned headers.

**Comment by phil16727** [comment]
Hi @michaelklishin 
There was indeed a spelling mistake in the Code. 
We used _ instead of -.
By the way is there somewhere a list of available Headers?

**Comment by michaelklishin** [comment]
All headers used by the STOMP plugin are mentioned in its respective doc guide.

**Comment by phil16727** [comment]
Hi @michaelklishin 
I wouldn’t have asked if I where able to find it. 
Any link you can share?

**Comment by michaelklishin** [comment]
[RabbitMQ STOMP plugin](https://www.rabbitmq.com/stomp.html).
