### ISSUE TITLE
Upgrade to latest Cowboy

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-web-stomp#13]
See https://github.com/rabbitmq/rabbitmq-server/issues/170.

**Comment by lemenkov** [comment]
Sorry for the noise - just subscribing on this.

**Comment by digipigeon** [comment]
+1

**Comment by sega-yarkin** [comment]
+1

**Comment by michaelklishin** [comment]
We have started working on this this week.

**Comment by essen** [comment]
Yep, working on it as we speak. :-)

**Comment by essen** [comment]
OK stopping for today, will finish on Monday. Small recap for me to remember when I get back to it:

* New wrapper for Ranch (https://github.com/rabbitmq/ranch-wrapper) - do we need to fork Ranch and keep a copy under rabbitmq/?
* New wrapper for Cowlib (https://github.com/rabbitmq/cowlib-wrapper) - same question
* Updated Cowboy wrapper (https://github.com/rabbitmq/cowboy-wrapper/compare/rabbitmq-web-stomp-13)
* Updated SockJS (https://github.com/essen/sockjs-erlang) - currently on a fork on my username, need to update the rabbitmq fork
* Updated SockJS wrapper (https://github.com/rabbitmq/sockjs-erlang-wrapper/compare/rabbitmq-web-stomp-13)
* Updated this very plugin (https://github.com/rabbitmq/rabbitmq-web-stomp/compare/rabbitmq-web-stomp-13)

Also need to update the public umbrella repo to add the two new wrappers, got it done on my local copy but it's simple enough that I can push that on Monday. I will also need to update the git URLs of everything to point to the right repositories.

Enjoy. :-)

**Comment by michaelklishin** [comment]
@essen we don't need to fork Ranch, Cowlib, etc but pinning them to the most recent stable release tag is a good idea.

**Comment by lemenkov** [comment]
@michaelklishin agree with that. Also relying on tags is much more easier for package maintainers.

**Comment by essen** [comment]
All PRs are open, and also pushed directly on master for ranch-wrapper and cowlib-wrapper (hoping there's no issue with that considering the repos were empty to begin with).

**Comment by michaelklishin** [comment]
Done in master. Good job, @essen!
