### ISSUE TITLE
Add raw Websocket support

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-web-stomp#17]
We want to add a new path, for example /ws, that would serve STOMP over raw Websocket, ie without the SockJS dependency.

Initially and by default it would serve STOMP, and later on it may be expanded to use different protocols (using Websocket's protocol header). There's however no need to take care of this until we have a second protocol to use.

The rabbitmq-web-stomp-examples plugin also needs to be updated and provide an alternative for each example for raw Websocket.

For the sake of simplicity, and to avoid duplicating code, I propose to do this in two steps:

* First the raw Websocket handler will simply call rabbit_ws_client when needed.
* Later on it might be worth implementing the STOMP decoding directly in the Websocket handler, if only to avoid wasting resources (there's really no need for a separate process there). It's also possible that this would be required to support STOMP hearbeats (#15) although that's just a guess at this point.

This ticket is about the first step.

**Comment by michaelklishin** [comment]
:+1: to `/ws`.

**Comment by essen** [comment]
Tasks left to do:

[ ] Rename rabbit_ws_h into rabbit_ws_handler (amend)
[ ] Rename rabbit_ws_sockjs into rabbit_sockjs_handler (new commit)
[ ] Update documentation at https://github.com/rabbitmq/rabbitmq-website/blob/master/site/web-stomp.md

**Comment by essen** [comment]
After looking in more details, rabbit_ws_sockjs is actually little about SockJS. It's basically starting the Cowboy listeners (including /ws) and then there's about 10 lines that are SockJS-specific. If it was to be split, I would prefer to do so in a different larger refactoring PR.

**Comment by michaelklishin** [comment]
@essen gotcha, lets tick that one off then and worry about it later (if at all).

**Comment by essen** [comment]
I think we're good now.
