### ISSUE TITLE
Cannot change address to bind to in configuration

### ISSUE THREAD

**Issue by asfaltboy** [rabbitmq/rabbitmq-web-stomp#2]
Currently only the post binding is settable:
```{rabbitmq_web_stomp, [{port, 12345}]}```

In some situations, something like this, is required:
```{rabbitmq_web_stomp, [{host, "192.168.1.10"}, {port, 12345}]}```

For instance when a single machine is listening on multiple IPs and we want to allow rabbitmq_web_stomp server to bind an address other than the default.

I don't know erland but I believe this should be fixed somewhere in https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/src/rabbit_ws_sockjs.erl somewhere around line 39:
```cowboy_tcp_transport, [{port,     Port}],```

**Comment by essen** [comment]
@michaelklishin This has been fixed by merging #22. Closing?
