### ISSUE TITLE
Tune keep-alive timeout

### ISSUE THREAD

**Issue by sega-yarkin** [rabbitmq/rabbitmq-web-stomp#21]
Before the web-stomp plugin we use the nginx and it configured to keeps many keep-alive connections (to save our resources and keep latency low), but when a connection idle near 5 seconds the cowboy close them. How we can change this timeout?

**Comment by sega-yarkin** [comment]
I found in cowboy's code that it's default timeout `get_value(timeout, Opts, 5000)`. It'll good if we can change this value, as well as change other ProtoOpts parameters, like `max_keepalive`. Thanks.

**Comment by michaelklishin** [comment]
@essen I'm closing this since it's a question but do we need to file a proper issue for this?

**Comment by michaelklishin** [comment]
@sega-yarkin I've mentioned this before: questions belong to the mailing list, not github issues.

**Comment by sega-yarkin** [comment]
@michaelklishin now we don't have some option in web-stomp plugin to change this behavior, I asked for append new one for that, it's like enhancement for plugin, not only question.

**Comment by michaelklishin** [comment]
@sega-yarkin I don't see how

```
How we can change this timeout?
```

is not a question. Anyway, if @essen believes this is still not possible in master, we'll file a specific issue.

**Comment by essen** [comment]
There's nothing in the plugin right now to configure Cowboy's behavior. Opened #22.

**Comment by michaelklishin** [comment]
#22 is now resolved, thank you @essen.
