### ISSUE TITLE
Allow configuring Cowboy behavior

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-web-stomp#22]
See #21. Should be a small change to rabbit_ws_sockjs. Not working today so will fill in more details later.

**Comment by essen** [comment]
Also related to #2.

Should we just add TCP options to the environment like we do in rabbitmq-server?

**Comment by michaelklishin** [comment]
@essen sounds good.

**Comment by essen** [comment]
Pushed https://github.com/rabbitmq/rabbitmq-web-stomp/tree/rabbitmq-web-stomp-22

A few remarks/questions:

* I updated the port in the code, it didn't look quite right compared to the port in the .app file and the docs, hope it's okay to do it as part of these changes
* Do you want me to add tests? I'm not sure what's the best way to test that kind of change but it's definitely possible (I can get inspiration from Cowboy tests I'm sure)
* Do we want these options documented on the website?

**Comment by michaelklishin** [comment]
@essen we do want these documented. [Updated fallback port](https://github.com/rabbitmq/rabbitmq-web-stomp/commit/134cc89021fa5fa5bc1a76215ad385d8493b2923) is OK, given that we refer to `15674` everywhere).

As for the tests, if you have an idea about adding some very basic tests (maybe something that asserts on application keys without even starting a listener), go for it. But it's one of those things that are a pain to test and pretty much never change.

**Comment by essen** [comment]
Pushed https://github.com/rabbitmq/rabbitmq-website/tree/rabbitmq-web-stomp-22 with the doc changes.

Tests... it's not trivial, so I will leave it at that for now. I want to get something up for most of these tickets first.

**Comment by michaelklishin** [comment]
Fixed in master.
