### ISSUE TITLE
Stomp processor changes broke Web STOMP

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-web-stomp#30]
This merge https://github.com/rabbitmq/rabbitmq-stomp/commit/d0393355e856158131fa7d0fbcf5f5e1d822abde from https://github.com/rabbitmq/rabbitmq-stomp/issues/6 with PR at https://github.com/rabbitmq/rabbitmq-stomp/pull/51

Currently Web STOMP does not work at all. The undef error here https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/src/rabbit_ws_client_sup.erl#L67 results in the SockJS application crashing entirely.

Not sure how the code should be changed.

**Comment by hairyhum** [comment]
There should be no `rabbit_stomp_processor` process anymore. So there is no `start_link` there.
