### ISSUE TITLE
Node shutdown issues with SSL

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-web-stomp#34]
None of this was in RabbitMQ 3.5.x, so it's not worth mentioning in the logs.

When running `q()` on a node that uses SSL, the node fails to stop because of a known issue in Ranch that happens under specific circumstances. A fix exists in the most recent Ranch release.

Another issue is that a lot of errors are sent to the logs. This is due to the number of acceptors being very large. It is also too large for the kind of connections we deal with. It will be reduced to 1 by default.

**Comment by michaelklishin** [comment]
@essen so the fix would be to upgrade Ranch and reduce the number of acceptors?

**Comment by essen** [comment]
That's what I'm about to send. :-)
