### ISSUE TITLE
SSL doesn't honor cowboy_opts

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-web-stomp#36]
TCP does: https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/src/rabbit_ws_sockjs.erl#L54
SSL doesn't: https://github.com/rabbitmq/rabbitmq-web-stomp/blob/master/src/rabbit_ws_sockjs.erl#L65

**Comment by michaelklishin** [comment]
Fixed in #38.
