### ISSUE TITLE
Incompatibile SockJS! Main site uses: "0.3.4", the iframe: "0.2.1".

### ISSUE THREAD

**Issue by redsquare** [rabbitmq/rabbitmq-web-stomp#4]
Currently socks js requests the iframe.html file and rabbitmq/cowboy responds with an old version which has a ref to sockjs 0.2.0 (http://cdn.sockjs.org/sockjs-0.2.js)

Can the iframe html be upgraded easily inside of rabbit?

**Comment by michaelklishin** [comment]
Not sure if this is still relevant but we should definitely make this documented and use the most recent SockJS version out of the box.

**Comment by essen** [comment]
This shouldn't be the case anymore (as far as I can see anyway), however we are not using the most recent version.

We are currently using 0.3 by default. There seems to be two more recent versions: 0.3.4 (upgrading there should be easy) and 1.0.3 (seems to be mostly packaging changes so is probably easy too).

I'll take a look.

**Comment by essen** [comment]
Scratch the previous comment: the file included was actually 0.3.4 (got confused by the filename "0.3"). The issue the OP had was apparently long fixed.

I am about to open PRs for two related things though:

* Update SockJS client to 1.0.3
* Update the documentation about sockjs_opts and sockjs_url

**Comment by essen** [comment]
Pushed three PRs updating to 1.0.3 and adding documentation about sockjs_opts.
