### ISSUE TITLE
Configuration doc request

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-web-stomp#46]
There are several configuration parameters for this module 
```
[{port, 15674},
 {tcp_config, []},
 {num_tcp_acceptors, 10},
 {ssl_config, []},
 {num_ssl_acceptors, 1},
 {cowboy_opts, []},
 {sockjs_opts, []},
 {ws_frame, text}]
```
@essen can you please give some explanation or links to docs about this parameters and some typical examples?

**Comment by essen** [comment]
I think it's all here: https://www.rabbitmq.com/web-stomp.html

Seems to be missing documentation for num_*_acceptors, which are the number of processes that will accept connections (unrelated to the maximum number of connections).

**Comment by hairyhum** [comment]
Thanks.
