### ISSUE TITLE
HTTP Basic auth logic not falling back on STOMP default user

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-web-stomp#60]
@essen 

With use_http_auth set to true, no Basic auth header and STOMP default user set. CONNECT without login/passcode errors out. Not Expected since it should succeed. It works if I use plain STOMP instead of web-stomp.

Config:

```
[ {rabbitmq_web_stomp, [{use_http_auth, true}]}, {rabbitmq_stomp, [{default_user, [{login, "guest"}, {passcode, "guest"}]}]} ].
```

STOMP frames:

```
Opening Web Socket...
Web Socket Opened...
>>> CONNECT
accept-version:1.1,1.0
heart-beat:10000,10000


<<< ERROR
message:Processing error
content-type:text/plain
version:1.0,1.1,1.2
content-length:16

Processing error
```

Related: Issue #43

**Comment by laurentluce** [comment]
@essen Were you able to reproduce this issue?  If yes, can we get an ETA on the fix.

**Comment by michaelklishin** [comment]
We do not make promises on ETA.

**Comment by laurentluce** [comment]
@michaelklishin I understand.

**Comment by essen** [comment]
I have opened two PRs implementing tests and a fix for this. It should work on all transports.
