### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by cboden** [rabbitmq/rabbitmq-web-stomp#8]
I know STOMP heartbeat can't work with SockJS but with many modern browsers taking over market share those that support native WebSockets are in the majority. 

Could this plugin be updated to have the option of disabling SockJS support and enabling server sent heartbeats?

**Comment by michaelklishin** [comment]
It can but we need to perform a major upgrade (Cowboy) first. this repo is a mirror, please post your request to rabbitmq-users. Thank you.
