### ISSUE TITLE
Proxy-protocol support 

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-web-stomp#84]
Similar to direct STOMP & AMQP, Web-STOMP listeners should also support proxy-protocol.

**Comment by michaelklishin** [comment]
Contributions are welcome :)

**Comment by michaelklishin** [comment]
Proxy protocol support in Ranch core is under consideration, let's wait until there's a decision.

**Comment by essen** [comment]
Ranch 1.7 is literally just the current Ranch + PROXY support so it's probably fine. :-)

As for this plugin I released Cowboy 2.6 today and will propose a patch to web stomp/mqtt tomorrow to be merged whenever Cowboy 2.6 gets used in RabbitMQ.

**Comment by essen** [comment]
Do we want a new `rabbitmq_web_stomp` option named `proxy_protocol` or is it enough to be able to specify it from `cowboy_opts`?

**Comment by essen** [comment]
No worries that was for next week. :-) Struggled writing a test in the meantime.

**Comment by essen** [comment]
I've opened a PR at https://github.com/rabbitmq/rabbitmq-web-stomp/pull/98 feel free to try, but note it'll probably be broken in AWS at the time being due to a bug in Ranch that will be fixed soon-ish.

**Comment by Ayanda-D** [comment]
cheers! 🤠
